<a href="https://colab.research.google.com/github/ameer-salam/Notes/blob/main/Data_Science_(Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Course - Mastering the Fundamentals


* **Uses of Python**
1. Data Science
2. Web developement
3. DBMS
4. Script writing
5. Building pipeline


* **What is Data Science**
involves running experiments, doing analysis and coming to conclusion iinvolved building models and testing them,
2.

* **How to do Data Science**
1. Extract Load Transform,
2. A/B testing,
3. Data Scraping and cleaning,
4. Doing analyses and presenting results,
5. Building and maintaining dashboards,
6. Building and deploying ML models.

## Numpy
1. **What is Numpy**
  1. Fundamental of every Data Science Library,
  2. it deals with the fundamental building blocks of all data science algos: **Vector and Matrices**

2. **When to use Numpy?**
  1. Optimizing to do Numerical Data science work,
  2. Numpy is a python library written in C, Making it blazingly fast.
  3. it has a lot of submodules capable of doing a variety of tasks related to Data science.

3. **When not to used Numpy**
  1. When you are working with non-numerical data,
  2. when data is in Text format,
  3. numpy runs on CPU while it cannot run on GPU wehn doing something like deep learning.

### Vectors and Matrices
1. **What is a vector**
It is a list of numbers
[1,3,5,3,2,8,]
* it is very similar to python list, but it is quite differnet
* in list you can have heterogenous elements
* vectors only support elements with same data types(Numeric datatypes),
* vectors are one dimensional.

2. **What is a matrix**
* matrix is a list of vectors (Collection of vectors)
* matric is multidimensional.
[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]


In [80]:
# code demo
import numpy as np
new_vector=np.array([1,2,3,4])
print(new_vector)

[1 2 3 4]


In [81]:
print(new_vector.shape)

(4,)


In [82]:
#multidimensioanl list
multi_dim_list=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(f"The multidimensional list is :",multi_dim_list, sep="\n")
print("The shape of this matrix is : ", multi_dim_list.shape)

The multidimensional list is :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The shape of this matrix is :  (3, 4)


In [83]:
#creating list with range
range_list = np.array([[range(1,6)],[range(6,11)]])
print(range_list)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


In [84]:
#numpy array with all zeros
zero_array=np.zeros((5,5))
print(zero_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [85]:
#array with ones
ones_arrays=np.ones((7,7))
print(ones_arrays)
print(ones_arrays.shape)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
(7, 7)


In [86]:
#using random function
rand_array=np.random.randint(90, size=(5,5))
print(rand_array)

[[49 40 49 12 80]
 [82 57 89 50 18]
 [20 32 75 81 12]
 [28 32 31 10  0]
 [41 28 10 34 61]]


### Data Types in Numpy
* unlike python, numpy have to have same datatype
* supported datatypes are:


| Data Type      | Variant     | Description                                                                 |
|----------------|-------------|-----------------------------------------------------------------------------|
| int            | int8, int16, int32, int64 | Integer data type with different bit sizes (8-bit, 16-bit, 32-bit, 64-bit). |
| uint           | uint8, uint16, uint32, uint64 | Unsigned integer data type with different bit sizes.                         |
| float          | float16, float32, float64 | Floating-point data type with different precision (16-bit, 32-bit, 64-bit).  |
| complex        | complex64, complex128 | Complex number data type with different precision (64-bit and 128-bit).      |
| bool           | -           | Boolean data type representing True or False values.                         |
| str            | -           | String data type representing text.                                         |
| object         | -           | Object data type for storing any Python object.                              |
| datetime64     | -           | Date and time data type with nanosecond precision.                           |
| timedelta64   | -            | Time difference data type representing the difference between two datetime64 values. |
| void           | -           | Raw data type for storing fixed-size blocks of memory.                       |


In [87]:
#numpy to create a list
num_exe=np.array([1,2,3,4,5,6])
print(num_exe)
print(num_exe.dtype)

[1 2 3 4 5 6]
int64


In [88]:
#numpy to create a flaot list
num_exe=np.array([1.6323,2.5734452,3.5653573746345,4.6734526472460,5.242454626,6.346378467355134])
print(num_exe)
print(num_exe.dtype)

[1.6323     2.5734452  3.56535737 4.67345265 5.24245463 6.34637847]
float64


In [89]:
#showcasing implicit conversion of string to integer
lst=[4,5,8,1,5,'4', '67']
new_lst=np.array(lst)
print(new_lst)
print(new_lst.dtype)

['4' '5' '8' '1' '5' '4' '67']
<U21


In [90]:
#explicit conversion to integer
new_lst=new_lst.astype(int)
print(new_lst)
print(new_lst.dtype)

[ 4  5  8  1  5  4 67]
int64


### Slicing of NumPy arrays
 * it is used for manipulating arrays
#### Masking -
Masking in NumPy refers to the process of creating a boolean array (mask) based on certain conditions applied to another array.

In [91]:
rand_array=np.random.rand(5,5)
print(rand_array)
print(rand_array.dtype)

[[0.31860841 0.27962823 0.68833295 0.93222778 0.37069962]
 [0.69219189 0.55153785 0.72265331 0.08647716 0.05455238]
 [0.37212885 0.16860587 0.4960026  0.68745574 0.06081677]
 [0.20713256 0.65696271 0.24674706 0.79773698 0.05892479]
 [0.32506843 0.55975611 0.85731585 0.86991796 0.10483157]]
float64


In [92]:
print(rand_array[2:])
print(rand_array.dtype)
print(rand_array[:2])
print(rand_array.dtype)

[[0.37212885 0.16860587 0.4960026  0.68745574 0.06081677]
 [0.20713256 0.65696271 0.24674706 0.79773698 0.05892479]
 [0.32506843 0.55975611 0.85731585 0.86991796 0.10483157]]
float64
[[0.31860841 0.27962823 0.68833295 0.93222778 0.37069962]
 [0.69219189 0.55153785 0.72265331 0.08647716 0.05455238]]
float64


In [93]:
#masking of array
arr=np.array([2,3,56,8,34,2,6,7,3,6,75,425,3,12,6,7,8])
mask=(arr%2)==0
new_list=arr[mask]
print("Oringinal array is : ", arr)
print("Array after masking is : ", new_list)

Oringinal array is :  [  2   3  56   8  34   2   6   7   3   6  75 425   3  12   6   7   8]
Array after masking is :  [ 2 56  8 34  2  6  6 12  6  8]


### Transpose of Matrix
* Converts rows into column and column into rows
* can change the shape of the original matrix

example matrix A=
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

now the transpose of thie matrix is
A=
[
    [1,4,7],
    [2,5,8],
    [3,6,9]
]

In [94]:
new_list=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(new_list)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
#transpose type 1
transpose_matrix=new_list.transpose()
print(transpose_matrix, "\n\n")

#transpose type 2
transpose_matrix=transpose_matrix.T
print(transpose_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]] 


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [96]:
#to perform calculation row-wise
sum_row=transpose_matrix.sum(axis=0)
print(sum_row, "\n\n")

[12 15 18] 




### Broadcasting
* broadcasting is the process of copying the matrix inorder to the the mathematical task done,
* it allows us to add matrix of different shapes and sizes,
*  it is only possible when the numebr of rows of both the matriz are the same,

In [97]:
new_list=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
new_small_matrix=np.array([[1],
                           [2],
                           [3]])
sum_matrix=new_list+new_small_matrix
print(sum_matrix)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


### Matrix multiplication
* GPU's help accelerate Matrix multiplication,
* number of columns at the LHS must be equal to the number of rows at the RHS

In [98]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

b=np.array([
    [1, 2, 3]
])

c=a*b
print(c)

b=b.T
c=a*b
print(b)
print(c)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[1]
 [2]
 [3]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


### **Tensors**
* matrix is a 2d array, while a tensor is a 3D array,
* they can also be 4d, 5d and so onn. but, they are generally 3d arrays
* scalars have zero dimensions
* Vectors have one dimensions (rows)
* matrix have two dimensions (rows and columns)
* tensors have multi dimensions (rows, columns and height)
* most common example of a 3d matrix(tensor) is a color image

#### Transpose of a tensor
* tensors transpose is obtained by rotating the 3d matrix (swaps dept and columns)



## Pandas
* it is used to read and manipulate the tabular data using data frames,
* it used numpy under the hood,
* similar to using SQL,
* Pandas can read data from files like CSV.
* Pandas cannot be used on **Non-tabular** data, image data, and when the data size exceeds 3gb as Pandas are not multithreaded

### DataFrames and Series
* DataFrame and Series are the two  main datastructures of Panadas:
* Series is a singel dimensional labelled data type, which can hold any type of element and each element can be indexed.
* DataFrame is basically a Tables, or combination of series
* Pandas follows a column first principle,


In [99]:
import pandas as pd
import numpy as np

a=[[1,2,3], [4,5,6], [7,8,9]]
arr=np.array(a)
print(a)

arrDF=pd.DataFrame(arr)
print(arrDF)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [100]:
marks=pd.DataFrame([{'Maths':3, 'Science':2}, {'Maths':3, 'Science':4}, {'Maths':4, 'Science':5}])
print(marks)

   Maths  Science
0      3        2
1      3        4
2      4        5


In [101]:
#to print just the maths marks
new_math=marks.Maths
print(new_math)

0    3
1    3
2    4
Name: Maths, dtype: int64


In [102]:
#Difference between the series and  dataframes
#print(marks.dtype)
print(type(marks))
print(type(marks.Maths))
print(marks.info())

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Maths    3 non-null      int64
 1   Science  3 non-null      int64
dtypes: int64(2)
memory usage: 176.0 bytes
None


In [103]:
#multiplying the dataframe to have same elements
marks=pd.DataFrame([{'Maths':3, 'Science':2}, {'Maths':3, 'Science':4}, {'Maths':4, 'Science':5}]*100)
print(marks)

     Maths  Science
0        3        2
1        3        4
2        4        5
3        3        2
4        3        4
..     ...      ...
295      3        4
296      4        5
297      3        2
298      3        4
299      4        5

[300 rows x 2 columns]


In [104]:
print(marks.head())

   Maths  Science
0      3        2
1      3        4
2      4        5
3      3        2
4      3        4


### Reading Data

| Data Format | Description                                              | Pandas Function                  |
|-------------|----------------------------------------------------------|----------------------------------|
| CSV         | Comma-separated values                                   | `pd.read_csv()`                  |
| Excel       | Microsoft Excel files (.xls or .xlsx)                    | `pd.read_excel()`                |
| JSON        | JavaScript Object Notation                               | `pd.read_json()`                 |
| HTML        | Hypertext Markup Language                                | `pd.read_html()`                 |
| SQL         | Structured Query Language                                | `pd.read_sql()`                  |
| HDF5        | Hierarchical Data Format version 5                       | `pd.read_hdf()`                  |
| Feather     | Feather binary columnar data format                      | `pd.read_feather()`              |
| Parquet     | Apache Parquet columnar storage format                   | `pd.read_parquet()`              |
| ORC         | Optimized Row Columnar (ORC) format                      | `pd.read_orc()`                  |
| Msgpack     | MessagePack serialized format                            | `pd.read_msgpack()`              |
| Stata       | Stata data files (.dta)                                   | `pd.read_stata()`                |
| SAS         | SAS datasets                                             | `pd.read_sas()`                  |
| SPSS        | SPSS datasets (.sav)                                      | `pd.read_spss()`                 |
| Google BigQuery | Google BigQuery SQL database                             | `pd.read_gbq()`                  |
| Clipboard   | Data copied to the clipboard                             | `pd.read_clipboard()`            |
| Pickle      | Python pickle format                                      | `pd.read_pickle()`               |
| Avro        | Apache Avro data serialization format                    | `pd.read_avro()`                 |
| Feather     | Feather binary columnar data format                      | `pd.read_feather()`              |
| Arrow       | Apache Arrow file format                                  | `pd.read_arrow()`                |
| MATLAB      | MATLAB data files (.mat)                                  | `pd.read_mat()`                  |
| YAML        | YAML (YAML Ain't Markup Language) format                  | `pd.read_yaml()`                 |


#### Datatype supported by Pandas

| Data Type    | Description                                        |
|--------------|----------------------------------------------------|
| int64        | Integer numbers                                    |
| float64      | Floating-point numbers                             |
| object       | Python objects (usually strings)                   |
| bool         | Boolean values (True or False)                     |
| datetime64   | Date and time values                               |
| timedelta64  | Differences between two datetime values            |
| category     | Categorical data (a fixed, finite set of values)   |

In [105]:
import pandas as pd
countries_covid_data=pd.read_csv("/content/sample_data/countries-aggregated.csv")
print(countries_covid_data)
print(type(countries_covid_data))

              Date      Country  Confirmed  Recovered  Deaths
0       2020-01-22  Afghanistan          0          0       0
1       2020-01-23  Afghanistan          0          0       0
2       2020-01-24  Afghanistan          0          0       0
3       2020-01-25  Afghanistan          0          0       0
4       2020-01-26  Afghanistan          0          0       0
...            ...          ...        ...        ...     ...
161563  2022-04-12     Zimbabwe     247094          0    5460
161564  2022-04-13     Zimbabwe     247160          0    5460
161565  2022-04-14     Zimbabwe     247208          0    5462
161566  2022-04-15     Zimbabwe     247237          0    5462
161567  2022-04-16     Zimbabwe     247237          0    5462

[161568 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>


In [106]:
#convert the data to date and time
countries_covid_data['Date']=pd.to_datetime(countries_covid_data["Date"])
print(countries_covid_data)

             Date      Country  Confirmed  Recovered  Deaths
0      2020-01-22  Afghanistan          0          0       0
1      2020-01-23  Afghanistan          0          0       0
2      2020-01-24  Afghanistan          0          0       0
3      2020-01-25  Afghanistan          0          0       0
4      2020-01-26  Afghanistan          0          0       0
...           ...          ...        ...        ...     ...
161563 2022-04-12     Zimbabwe     247094          0    5460
161564 2022-04-13     Zimbabwe     247160          0    5460
161565 2022-04-14     Zimbabwe     247208          0    5462
161566 2022-04-15     Zimbabwe     247237          0    5462
161567 2022-04-16     Zimbabwe     247237          0    5462

[161568 rows x 5 columns]


In [107]:
countries_covid_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161568 entries, 0 to 161567
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype         
---  ------     --------------   -----         
 0   Date       161568 non-null  datetime64[ns]
 1   Country    161568 non-null  object        
 2   Confirmed  161568 non-null  int64         
 3   Recovered  161568 non-null  int64         
 4   Deaths     161568 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 6.2+ MB


In [108]:
#finding how mmany unique values
print(f"How many Dates : ", countries_covid_data["Date"].nunique())
print(f"How many Country : ", countries_covid_data["Country"].nunique())

How many Dates :  816
How many Country :  198


### DataFrane indexing
* it is an analgous  to python list index,
* in DataFranes, you can also use String for indexing,
* DataFrame indexing is performed using `iloc` and `loc`