<a href="https://colab.research.google.com/github/ameer-salam/Notes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
Stands for Numerical Python which is a core library for numeric and scientific calculation
* it containt multidimensional array aobjects and collection of routines(Functions) for processing those arrays


## Creating arrays


In [ ]:
import numpy as np
import  random

a=np.array([1,2,3,4,5,6], dtype=int)
print("Single dimensional array : ", a)

Single dimensional array :  [1 2 3 4 5 6]


In [ ]:
#creating multi-dim array with lists
m=np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]], dtype=int)
print("Multi dimensional array : ", m)

Multi dimensional array :  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Creatin matrix with ones and Zeros


In [ ]:
#creating a 2x2 array with all elements as 1
o=np.ones((2,2))
print("\n", o)


 [[1. 1.]
 [1. 1.]]


In [ ]:
#creating a 3x3 array with all elements as 0
z=np.zeros((2,2))
print("\n", z)


 [[0. 0.]
 [0. 0.]]


### Initialize Arrays with same elements

In [ ]:
#initialize the numpay arrays with  the same numbers
s=np.full((3,3), 10)
print("\n", s)


 [[10 10 10]
 [10 10 10]
 [10 10 10]]


### Initialize Arrays with range function

In [ ]:
#initializing single dimension np array with range
r=np.arange(10, 21)
print("\n", r)


 [10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#initializing single dimension np array with skip value
r1=np.arange(10, 51, 5)
print("\n", r1)


 [10 15 20 25 30 35 40 45 50]


### Initialize Arrays with Random function

In [ ]:
#initialize with Random numbers
ra=np.random.randint(1, 50, 5)
print("\n", ra)


 [42  2 41 44 43]


In [ ]:
#initialize multidimensional array with Random numbers
ra=np.random.randint(1, 50, (5,5))
print("\n", ra)


 [[16  6 49 26 24]
 [21 41 23 24 45]
 [28 20 36 22 11]
 [45 21 41  8 29]
 [ 8 11 11 44 38]]


## Numpy Operations

NumPy arrays support a wide range of operations for efficient numerical computing. Here's a summary of some of the key operations available for NumPy arrays:

1. **Element-wise Operations**:
   - Arithmetic operations: Addition (`+`), subtraction (`-`), multiplication (`*`), division (`/`), exponentiation (`**`), etc.
   - Trigonometric functions: `numpy.sin()`, `numpy.cos()`, `numpy.tan()`, `numpy.arcsin()`, `numpy.arccos()`, `numpy.arctan()`, etc.
   - Exponential and logarithmic functions: `numpy.exp()`, `numpy.log()`, `numpy.log10()`, `numpy.log2()`, etc.
   - Absolute value: `numpy.abs()`
   - Rounding: `numpy.round()`, `numpy.floor()`, `numpy.ceil()`, etc.
   - Comparison operations: `==`, `!=`, `<`, `<=`, `>`, `>=`, etc.
   - Element-wise logical operations: `numpy.logical_and()`, `numpy.logical_or()`, `numpy.logical_not()`, etc.
   
2. **Reduction Operations**:
   - Summation: `numpy.sum()`
   - Mean: `numpy.mean()`
   - Standard deviation: `numpy.std()`
   - Variance: `numpy.var()`
   - Minimum: `numpy.min()`
   - Maximum: `numpy.max()`
   - Median: `numpy.median()`
   - Percentiles: `numpy.percentile()`
   - Cumulative sum: `numpy.cumsum()`
   - Cumulative product: `numpy.cumprod()`

3. **Linear Algebra Operations**:
   - Matrix multiplication: `numpy.dot()`, `@` operator (Python 3.5+)
   - Transpose: `numpy.transpose()`, `.T` attribute
   - Inverse: `numpy.linalg.inv()`
   - Determinant: `numpy.linalg.det()`
   - Eigenvalues and eigenvectors: `numpy.linalg.eig()`
   - Singular Value Decomposition (SVD): `numpy.linalg.svd()`
   - Solving linear equations: `numpy.linalg.solve()`

4. **Array Manipulation Operations**:
   - Reshaping: `numpy.reshape()`
   - Flattening: `numpy.flatten()`, `numpy.ravel()`
   - Concatenation: `numpy.concatenate()`, `numpy.stack()`
   - Splitting: `numpy.split()`, `numpy.array_split()`
   - Transposition: `numpy.transpose()`, `.T` attribute

5. **Random Number Generation**:
   - Random samples from various distributions: `numpy.random.rand()`, `numpy.random.randn()`, `numpy.random.randint()`, `numpy.random.uniform()`, `numpy.random.normal()`, etc.

### Operations on Shape

### Check the shape of numpy array and change it

In [ ]:
# checking the shape of the array
import numpy as np
import random
a=np.random.randint(2,67, (3,2))
print(a)
print("The Shape of the Array is : ", a.shape)

# to change the shape of the np array
a.shape=(2,3)
print("Array after changing the shape : ", a)

[[62 16]
 [60 42]
 [54 21]]
The Shape of the Array is :  (3, 2)
Array after changing the shape :  [[62 16 60]
 [42 54 21]]


### Stacking methods
* In NumPy, stacking methods refer to functions that are used to concatenate or stack arrays along a specified axis. These methods allow you to combine multiple arrays into a single array, either by stacking them vertically (along the row axis) or horizontally (along the column axis).

* Stacking methods are
1. **Combining** - combining data from different data sources or data structures into a single array.
2. **Creating multidimensional arrays** - you can create higher dimension arrays from lower dinemsion arrays
3. **Preparing data for Machine learning** - while trainging a ML model, you need to provide mulitple features arrays as one array, and with stacking methods you can oncatinate these arrays and create single input array
4. **Data Visualization** - combine multiple data sets for plotting,
5. **Array Manipulation** - reshaping, splitting, and transposing arrays.


#### Different Stacking methods are:
1. numpy.vstack() - Stack vertically
2. numpy.hstack() - Stack horizontally
3. numpy.dstack() - depth-wise stacking
4. numpy.stack()  - along a new axis
5. numpy.column_stack()  - arranges the np arrays (rows) into columns



In [ ]:
import numpy as np

a=np.array([10,20,30,40,50],)
a.shape=(5,1)
b=np.array([60,70,80,90,100])
b.shape=(5,1)
print("Array A is : ", a, "\nArray B is : ", b,'\n')

Array A is :  [[10]
 [20]
 [30]
 [40]
 [50]] 
Array B is :  [[ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]] 



In [ ]:
#vertical stacking
vs=np.vstack((a, b))
print("Stacking done one above another : \n", vs)

Stacking done one above another : 
 [[ 10]
 [ 20]
 [ 30]
 [ 40]
 [ 50]
 [ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]]


In [ ]:
#horizontal shapping

a.shape=b.shape=(1,5)
print("Array A is : ", a, "\nArray B is : ", b,'\n')
hs=np.hstack((a, b))
print("After Horizontal shapping : \n", hs)

Array A is :  [[10 20 30 40 50]] 
Array B is :  [[ 60  70  80  90 100]] 

After Horizontal shapping : 
 [[ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
#column shapping
a.shape=b.shape=(5,1)
print("Array A is : \n", a, "\nArray B is : \n", b,'\n')
cs=np.column_stack((a, b))
print("After Column shapping : \n", cs)

Array A is : 
 [[10]
 [20]
 [30]
 [40]
 [50]] 
Array B is : 
 [[ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]] 

After Column shapping : 
 [[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


### Intersection and Difference of sets


In [ ]:
#intersection
n1=np.array([1,2,3,4,5])
n2=np.array([3,4,5,6,7])

#intersection
i=np.intersect1d(n1, n2)
print("The common Elements in n1 and n2 are : ", i)

The common Elements in n1 and n2 are :  [3 4 5]


In [ ]:
#difference

#difference (to find elements unique to only n1)
d1=np.setdiff1d(n1, n2)
print("The elements unique to only n1 are : ", d1)

#difference (to find elements unique to only n2)
d2=np.setdiff1d(n2, n1)
print("The elements unique to only n2 are : ", d2)

The elements unique to only n1 are :  [1 2]
The elements unique to only n2 are :  [6 7]


## NumPy Mathematics


### Sum of numpy arrays


In [ ]:
# adding two numpy array
n1=np.array([[1,2,3,4,5], [6,7,8,9,10]])
n2=np.array([[11,12,13,14,15], [16,17,18,19,20]])
print("Sum of A = ", np.sum(n1), "\nSum of B = ", np.sum(n2))
sum=np.sum([n1, n2]) # axis=0 - Row, axis=1 - column, axis=2 - depth
print("Sum of A and B is : ", sum)

Sum of A =  55 
Sum of B =  155
Sum of A and B is :  [[ 7  9 11 13 15]
 [27 29 31 33 35]]


In [ ]:
#finding the sum of np array at a given axis

#row sum
sum=np.sum([n1, n2], axis=0)
print("Sum of Rows : \n", sum)

#column sum
sum=np.sum([n1, n2], axis=1)
print("\n\nSum of Columns : \n", sum)

Sum of Rows : 
 [[12 14 16 18 20]
 [22 24 26 28 30]]


Sum of Columns : 
 [[ 7  9 11 13 15]
 [27 29 31 33 35]]


### Scalar operations on NumPy arrays


In [ ]:
#basic addition
print(n1)
n12=n1+1
print("n1 after basic addition is : \n", n12)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
n1 after basic addition is : 
 [[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


In [ ]:
#basic subtraction
print(n2)
n22=n2-1
print("n1 after basic subtraction is : \n", n22)

[[11 12 13 14 15]
 [16 17 18 19 20]]
n1 after basic subtraction is : 
 [[10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
#basic multiplication
print(n2)
n22=n2*2
print("\nn1 after basic subtraction is : \n", n22)

[[11 12 13 14 15]
 [16 17 18 19 20]]

n1 after basic subtraction is : 
 [[22 24 26 28 30]
 [32 34 36 38 40]]


In [ ]:
#basic division
print(n2)
n22=n2/2
print("\nn1 after basic division is : \n", n22)

[[11 12 13 14 15]
 [16 17 18 19 20]]

n1 after basic division is : 
 [[ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]]


### Mean, Median, Standar Deviation


In [ ]:
#mean

m=np.mean(n22)
print("The mean of n22 is = ", m)

m=np.mean([n1, n22])
print("The mean of n1 and n22 is = ", m)

The mean of n22 is =  7.75
The mean of n1 and n2 is =  6.625


In [ ]:
#median

m=np.median(n22)
print("The median of n22 is = ", m)

m=np.median([n1, n22])
print("The median of n1 and n22 is = ", m)

The median of n22 is =  7.75
The median of n1 and n2 is =  7.0


In [ ]:
#Standard Deviation

m=np.std(n22)
print("The Standard Deviation of n22 is = ", m)

m=np.std([n1, n22])
print("The Standard Deviation of n1 and n22 is = ", m)

The Standard Deviation of n22 is =  1.4361406616345072
The Standard Deviation of n1 and n22 is =  2.5341418665891617


## Numpy Matrix

### Row and Column indexing (Slicing)

In [ ]:
#creating a numpy matrix

#Extracting romm
m=np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15]], dtype=int)
print("The array Created is : \n", m)
print("\nAccessing first Row of the Matrix A : \n", m[0])
print("\nAccessing third Row of the Matrix A : \n", m[2])

#extracting column
#slicing
print("\nAll elements of first columns of all rows are : \n", m[:,:1])
print("\nAll elements of third columns of all rows are : \n", m[:,2:3])

The array Created is : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Accessing first Row of the Matrix A : 
 [1 2 3 4 5]

Accessing third Row of the Matrix A : 
 [11 12 13 14 15]

All elements of first columns of all rows are : 
 [[ 1]
 [ 6]
 [11]]

All elements of third columns of all rows are : 
 [[ 3]
 [ 8]
 [13]]


### Transpose of a Matrix


In [ ]:
print("m matrix before transpose : \n", m)
print("m matrix after transpose : \n", m.transpose())


m matrix before transpose : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
m matrix after transpose : 
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### Matrix Multiplication


In [ ]:
#multiplocation (dot operation)

print("\nMatrix n1 = \n",n1,"\nShape of n1 is : ",np.shape(n1), "\n\nMatrix n2 = \n", n2,"\nShape of n2 is : ",np.shape(n1))

#matrix multiplication
print("After performing dot operation : ", np.dot(n1, n2.transpose()))



Matrix n1 = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 
Shape of n1 is :  (2, 5) 

Matrix n2 = 
 [[11 12 13 14 15]
 [16 17 18 19 20]] 
Shape of n2 is :  (2, 5)
After performing dot operation :  [[205 280]
 [530 730]]


## Saving and Loading the numpy array

In [ ]:
print("The n1 arrays is : \n", n1)

#saving the numpy array
np.save("my_numpy", n1)

The n1 arrays is : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#loading the numpy

new_np=np.load("my_numpy.npy")
print("The new array which has its elements loaded from my_numpy is : \n", new_np)

The new array which has its elements loaded from my_numpy is : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
