<a href="https://colab.research.google.com/github/ameer-salam/Notes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
Stands for Numerical Python which is a core library for numeric and scientific calculation
* it containt multidimensional array aobjects and collection of routines(Functions) for processing those arrays


## Creating arrays


In [40]:
import numpy as np
import  random

a=np.array([1,2,3,4,5,6], dtype=int)
print("Single dimensional array : ", a)

Single dimensional array :  [1 2 3 4 5 6]


In [39]:
#creating multi-dim array with lists
m=np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]], dtype=int)
print("Multi dimensional array : ", m)

Multi dimensional array :  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Creatin matrix with ones and Zeros


In [32]:
#creating a 2x2 array with all elements as 1
o=np.ones((2,2))
print("\n", o)


 [[1. 1.]
 [1. 1.]]


In [33]:
#creating a 3x3 array with all elements as 0
z=np.zeros((2,2))
print("\n", z)


 [[0. 0.]
 [0. 0.]]


### Initialize Arrays with same elements

In [34]:
#initialize the numpay arrays with  the same numbers
s=np.full((3,3), 10)
print("\n", s)


 [[10 10 10]
 [10 10 10]
 [10 10 10]]


### Initialize Arrays with range function

In [35]:
#initializing single dimension np array with range
r=np.arange(10, 21)
print("\n", r)


 [10 11 12 13 14 15 16 17 18 19 20]


In [36]:
#initializing single dimension np array with skip value
r1=np.arange(10, 51, 5)
print("\n", r1)


 [10 15 20 25 30 35 40 45 50]


### Initialize Arrays with Random function

In [37]:
#initialize with Random numbers
ra=np.random.randint(1, 50, 5)
print("\n", ra)


 [42  2 41 44 43]


In [38]:
#initialize multidimensional array with Random numbers
ra=np.random.randint(1, 50, (5,5))
print("\n", ra)


 [[16  6 49 26 24]
 [21 41 23 24 45]
 [28 20 36 22 11]
 [45 21 41  8 29]
 [ 8 11 11 44 38]]


## Numpy Operations

NumPy arrays support a wide range of operations for efficient numerical computing. Here's a summary of some of the key operations available for NumPy arrays:

1. **Element-wise Operations**:
   - Arithmetic operations: Addition (`+`), subtraction (`-`), multiplication (`*`), division (`/`), exponentiation (`**`), etc.
   - Trigonometric functions: `numpy.sin()`, `numpy.cos()`, `numpy.tan()`, `numpy.arcsin()`, `numpy.arccos()`, `numpy.arctan()`, etc.
   - Exponential and logarithmic functions: `numpy.exp()`, `numpy.log()`, `numpy.log10()`, `numpy.log2()`, etc.
   - Absolute value: `numpy.abs()`
   - Rounding: `numpy.round()`, `numpy.floor()`, `numpy.ceil()`, etc.
   - Comparison operations: `==`, `!=`, `<`, `<=`, `>`, `>=`, etc.
   - Element-wise logical operations: `numpy.logical_and()`, `numpy.logical_or()`, `numpy.logical_not()`, etc.
   
2. **Reduction Operations**:
   - Summation: `numpy.sum()`
   - Mean: `numpy.mean()`
   - Standard deviation: `numpy.std()`
   - Variance: `numpy.var()`
   - Minimum: `numpy.min()`
   - Maximum: `numpy.max()`
   - Median: `numpy.median()`
   - Percentiles: `numpy.percentile()`
   - Cumulative sum: `numpy.cumsum()`
   - Cumulative product: `numpy.cumprod()`

3. **Linear Algebra Operations**:
   - Matrix multiplication: `numpy.dot()`, `@` operator (Python 3.5+)
   - Transpose: `numpy.transpose()`, `.T` attribute
   - Inverse: `numpy.linalg.inv()`
   - Determinant: `numpy.linalg.det()`
   - Eigenvalues and eigenvectors: `numpy.linalg.eig()`
   - Singular Value Decomposition (SVD): `numpy.linalg.svd()`
   - Solving linear equations: `numpy.linalg.solve()`

4. **Array Manipulation Operations**:
   - Reshaping: `numpy.reshape()`
   - Flattening: `numpy.flatten()`, `numpy.ravel()`
   - Concatenation: `numpy.concatenate()`, `numpy.stack()`
   - Splitting: `numpy.split()`, `numpy.array_split()`
   - Transposition: `numpy.transpose()`, `.T` attribute

5. **Random Number Generation**:
   - Random samples from various distributions: `numpy.random.rand()`, `numpy.random.randn()`, `numpy.random.randint()`, `numpy.random.uniform()`, `numpy.random.normal()`, etc.

### Operations on Shape

### Check the shape of numpy array and change it

In [5]:
# checking the shape of the array
import numpy as np
import random
a=np.random.randint(2,67, (3,2))
print(a)
print("The Shape of the Array is : ", a.shape)

# to change the shape of the np array
a.shape=(2,3)
print("Array after changing the shape : ", a)

[[62 16]
 [60 42]
 [54 21]]
The Shape of the Array is :  (3, 2)
Array after changing the shape :  [[62 16 60]
 [42 54 21]]


### Stacking methods
* In NumPy, stacking methods refer to functions that are used to concatenate or stack arrays along a specified axis. These methods allow you to combine multiple arrays into a single array, either by stacking them vertically (along the row axis) or horizontally (along the column axis).

* Stacking methods are
1. **Combining** - combining data from different data sources or data structures into a single array.
2. **Creating multidimensional arrays** - you can create higher dimension arrays from lower dinemsion arrays
3. **Preparing data for Machine learning** - while trainging a ML model, you need to provide mulitple features arrays as one array, and with stacking methods you can oncatinate these arrays and create single input array
4. **Data Visualization** - combine multiple data sets for plotting,
5. **Array Manipulation** - reshaping, splitting, and transposing arrays.


#### Different Stacking methods are:
1. numpy.vstack() - Stack vertically
2. numpy.hstack() - Stack horizontally
3. numpy.dstack() - depth-wise stacking
4. numpy.stack()  - along a new axis
5. numpy.column_stack()  - arranges the np arrays (rows) into columns



In [17]:
import numpy as np

a=np.array([10,20,30,40,50],)
a.shape=(5,1)
b=np.array([60,70,80,90,100])
b.shape=(5,1)
print("Array A is : ", a, "\nArray B is : ", b,'\n')

Array A is :  [[10]
 [20]
 [30]
 [40]
 [50]] 
Array B is :  [[ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]] 



In [19]:
#vertical stacking
vs=np.vstack((a, b))
print("Stacking done one above another : \n", vs)

Stacking done one above another : 
 [[ 10]
 [ 20]
 [ 30]
 [ 40]
 [ 50]
 [ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]]


In [24]:
#horizontal shapping

a.shape=b.shape=(1,5)
print("Array A is : ", a, "\nArray B is : ", b,'\n')
hs=np.hstack((a, b))
print("After Horizontal shapping : \n", hs)

Array A is :  [[10 20 30 40 50]] 
Array B is :  [[ 60  70  80  90 100]] 

After Horizontal shapping : 
 [[ 10  20  30  40  50  60  70  80  90 100]]


In [28]:
#column shapping
a.shape=b.shape=(5,1)
print("Array A is : \n", a, "\nArray B is : \n", b,'\n')
cs=np.column_stack((a, b))
print("After Column shapping : \n", cs)

Array A is : 
 [[10]
 [20]
 [30]
 [40]
 [50]] 
Array B is : 
 [[ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]] 

After Column shapping : 
 [[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


### Intersection and Difference of sets


In [31]:
#intersection
n1=np.array([1,2,3,4,5])
n2=np.array([3,4,5,6,7])

#intersection
i=np.intersect1d(n1, n2)
print("The common Elements in n1 and n2 are : ", i)

The common Elements in n1 and n2 are :  [3 4 5]


In [32]:
#difference

#difference (to find elements unique to only n1)
d1=np.setdiff1d(n1, n2)
print("The elements unique to only n1 are : ", d1)

#difference (to find elements unique to only n2)
d2=np.setdiff1d(n2, n1)
print("The elements unique to only n2 are : ", d2)

The elements unique to only n1 are :  [1 2]
The elements unique to only n2 are :  [6 7]
